# Generated by Django 6.0.2 on 2026-02-19 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('room_type', models.CharField(choices=[('study', 'Study Group'), ('project', 'Project'), ('tutoring', 'Tutoring')], default='study', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('level', models.IntegerField(choices=[(100, 'Year 1'), (200, 'Year 2'), (300, 'Year 3'), (400, 'Year 4'), (500, 'Postgraduate')])),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('programming', 'Programming'), ('mathematics', 'Mathematics'), ('science', 'Science'), ('language', 'Language'), ('design', 'Design'), ('business', 'Business'), ('engineering', 'Engineering'), ('other', 'Other')], default='other', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('resource_type', models.CharField(choices=[('textbook', 'Textbook'), ('video', 'Video Lecture'), ('article', 'Article'), ('tutorial', 'Tutorial'), ('paper', 'Research Paper'), ('tool', 'Tool/Software'), ('course_material', 'Course Material')], max_length=20)),
                ('url', models.URLField(blank=True, default='')),
                ('tags', models.TextField(blank=True, default='', help_text='Comma-separated tags')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('rating', models.FloatField(default=0.0)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_courses', models.ManyToManyField(blank=True, related_name='resources', to='api.course')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_skills', models.ManyToManyField(blank=True, related_name='resources', to='api.skill')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='')),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('university', models.CharField(default='University of Nairobi', max_length=200)),
                ('department', models.CharField(default='', max_length=200)),
                ('year_of_study', models.IntegerField(default=1)),
                ('gpa', models.FloatField(default=0.0)),
                ('interests', models.TextField(blank=True, default='', help_text='Comma-separated interests')),
                ('learning_goals', models.TextField(blank=True, default='', help_text='What the student wants to learn')),
                ('collaboration_preference', models.CharField(choices=[('study_group', 'Study Group'), ('project', 'Project Partner'), ('tutoring', 'Tutoring'), ('research', 'Research'), ('any', 'Any')], default='any', max_length=20)),
                ('available_hours_per_week', models.IntegerField(default=10)),
                ('preferred_time', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('flexible', 'Flexible')], default='flexible', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='students', to='api.course')),
                ('skills', models.ManyToManyField(blank=True, related_name='students', to='api.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.collaborationroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studentprofile')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='collaborationroom',
            name='members',
            field=models.ManyToManyField(related_name='rooms', to='api.studentprofile'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('match_reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='suggested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_a', to='api.studentprofile')),
                ('student_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_b', to='api.studentprofile')),
            ],
            options={
                'ordering': ['-similarity_score'],
                'unique_together': {('student_a', 'student_b')},
            },
        ),
    ]
