# Generated by Django 6.0.2 on 2026-02-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_resource_file_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_emoji', models.CharField(max_length=10)),
                ('requirement_type', models.CharField(max_length=50)),
                ('requirement_threshold', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='current_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='total_xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='badges',
            field=models.ManyToManyField(blank=True, related_name='students', to='api.badge'),
        ),
    ]
