# Generated by Django 6.0.2 on 2026-03-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_emailverificationcode'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='api_notific_recipie_5c719b_idx',
            old_name='api_notific_recipie_f34798_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='api_notific_recipie_0f27ac_idx',
            old_name='api_notific_recipie_286696_idx',
        ),
        migrations.AlterField(
            model_name='collaborationroom',
            name='room_type',
            field=models.CharField(choices=[('direct', 'Direct Message'), ('study', 'Study Group'), ('project', 'Project'), ('tutoring', 'Tutoring')], default='study', max_length=20),
        ),
    ]
