# Generated by Django 6.0.2 on 2026-03-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='show_personal_info',
            field=models.BooleanField(default=False, help_text='If True, allow other users to see personal info (name, email, avatar).'),
        ),
    ]
