# Generated by Django 5.2.6 on 2026-07-21 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_matchinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshTokenRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=255, unique=True)),
                ('family', models.CharField(default='8d7c362f9d3c44a799e860568d709492', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked', models.BooleanField(default=False)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameIndex(
            model_name='matchinvite',
            new_name='api_matchin_recipie_1d704b_idx',
            old_name='api_matchin_recipie_6547e0_idx',
        ),
        migrations.RenameIndex(
            model_name='matchinvite',
            new_name='api_matchin_sender__9dd3a6_idx',
            old_name='api_matchin_sender__2fd57e_idx',
        ),
        migrations.AddField(
            model_name='refreshtokenrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='refreshtokenrecord',
            index=models.Index(fields=['user', 'revoked'], name='api_refresh_user_id_9c68b4_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtokenrecord',
            index=models.Index(fields=['family'], name='api_refresh_family_648839_idx'),
        ),
    ]
